#Action cable uses Redis by defaulft to adminster connections,channels, and sending/receiving messages over the WebSocket.

production:
  adapter: redis 
  url: <% ENV["REDISCLOUD_URL"] %>

  development:
    adapter: async

  test:
    adapter: async